using LonghornCinemaFinalProject.Models;
using LonghornCinemaFinalProject.DAL;
using System.Data.Entity.Migrations;
using System;
using System.Linq;

namespace LonghornCinemaFinalProject.Migrations
{
    public class UserData
    {
        public void SeedAppUsers(AppDbContext db)
        {
            User c1 = new User();
            c1.LastName = "Baker";
            c1.FirstName = "Christopher";
            c1.Email = "cbaker@example.com";
            c1.Password = "hello1";
            c1.Birthday = new DateTime(1949, 11, 23);
            c1.StreetAddress = "1245 Lake Anchorage Blvd.";
            c1.City = "Austin";
            c1.State = "TX";
            c1.ZipCode = 78705;
            c1.PhoneNumber = "5125550180";
            c1.PopcornPointsBalance = 110;
            db.AppUsers.AddOrUpdate(c => c.LastName, c1);
            db.SaveChanges();

            User c2 = new User();
            c2.LastName = "Banks";
            c2.FirstName = "Michelle";
            c2.Email = "banker@longhorn.net";
            c2.Password = "potato";
            c2.Birthday = new DateTime(1962, 11, 27);
            c2.StreetAddress = "1300 Tall Pine Lane";
            c2.City = "Austin";
            c2.State = "TX";
            c2.ZipCode = 78712;
            c2.PhoneNumber = "5125550183";
            c2.PopcornPointsBalance = 40;
            db.AppUsers.AddOrUpdate(c => c.LastName, c2);
            db.SaveChanges();

            User c3 = new User();
            c3.LastName = "Broccolo";
            c3.FirstName = "Franco";
            c3.Email = "franco@example.com";
            c3.Password = "painting";
            c3.Birthday = new DateTime(1992, 10, 11);
            c3.StreetAddress = "62 Browning Road";
            c3.City = "Austin";
            c3.State = "TX";
            c3.ZipCode = 78704;
            c3.PhoneNumber = "5125550128";
            c3.PopcornPointsBalance = 30;
            db.AppUsers.AddOrUpdate(c => c.LastName, c3);
            db.SaveChanges();

            User c4 = new User();
            c4.LastName = "Chang";
            c4.FirstName = "Wendy";
            c4.Email = "wchang@example.com";
            c4.Password = "texas1";
            c4.Birthday = new DateTime(1997, 5, 16);
            c4.StreetAddress = "202 Bellmont Hall";
            c4.City = "Round Rock";
            c4.State = "TX";
            c4.ZipCode = 78681;
            c4.PhoneNumber = "5125550133";
            c4.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(c => c.LastName, c4);
            db.SaveChanges();

            User c5 = new User();
            c5.LastName = "Chou";
            c5.FirstName = "Lim";
            c5.Email = "limchou@gogle.com";
            c5.Password = "Anchorage";
            c5.Birthday = new DateTime(1970, 4, 6);
            c5.StreetAddress = "1600 Teresa Lane";
            c5.City = "Austin";
            c5.State = "TX";
            c5.ZipCode = 78705;
            c5.PhoneNumber = "5125550102";
            c5.PopcornPointsBalance = 40;
            db.AppUsers.AddOrUpdate(c => c.LastName, c5);
            db.SaveChanges();

            User c6 = new User();
            c6.LastName = "Dixon";
            c6.FirstName = "Shan";
            c6.Email = "shdixon@aoll.com";
            c6.Password = "pepperoni";
            c6.Birthday = new DateTime(1984, 1, 12);
            c6.StreetAddress = "234 Holston Circle";
            c6.City = "Austin";
            c6.State = "TX";
            c6.ZipCode = 78712;
            c6.PhoneNumber = "5125550146";
            c6.PopcornPointsBalance = 20;
            db.AppUsers.AddOrUpdate(c => c.LastName, c6);
            db.SaveChanges();

            User c7 = new User();
            c7.LastName = "Evans";
            c7.FirstName = "Jim Bob";
            c7.Email = "j.b.evans@aheca.org";
            c7.Password = "longhorns";
            c7.Birthday = new DateTime(1959, 9, 9);
            c7.StreetAddress = "506 Farrell Circle";
            c7.City = "Georgetown";
            c7.State = "TX";
            c7.ZipCode = 78628;
            c7.PhoneNumber = "5125550170";
            c7.PopcornPointsBalance = 50;
            db.AppUsers.AddOrUpdate(c => c.LastName, c7);
            db.SaveChanges();

            User c8 = new User();
            c8.LastName = "Feeley";
            c8.FirstName = "Lou Ann";
            c8.Email = "feeley@penguin.org";
            c8.Password = "aggies";
            c8.Birthday = new DateTime(2001, 1, 12);
            c8.StreetAddress = "600 S 8th Street W";
            c8.City = "Austin";
            c8.State = "TX";
            c8.ZipCode = 78746;
            c8.PhoneNumber = "5125550105";
            c8.PopcornPointsBalance = 170;
            db.AppUsers.AddOrUpdate(c => c.LastName, c8);
            db.SaveChanges();

            User c9 = new User();
            c9.LastName = "Freeley";
            c9.FirstName = "Tesa";
            c9.Email = "tfreeley@minnetonka.ci.us";
            c9.Password = "raiders";
            c9.Birthday = new DateTime(1991, 2, 4);
            c9.StreetAddress = "4448 Fairview Ave.";
            c9.City = "Horseshoe Bay";
            c9.State = "TX";
            c9.ZipCode = 78657;
            c9.PhoneNumber = "5125550114";
            c9.PopcornPointsBalance = 160;
            db.AppUsers.AddOrUpdate(c => c.LastName, c9);
            db.SaveChanges();

            User c10 = new User();
            c10.LastName = "Garcia";
            c10.FirstName = "Margaret";
            c10.Email = "mgarcia@gogle.com";
            c10.Password = "mustangs";
            c10.Birthday = new DateTime(1991, 10, 2);
            c10.StreetAddress = "594 Longview";
            c10.City = "Austin";
            c10.State = "TX";
            c10.ZipCode = 78727;
            c10.PhoneNumber = "5125550155";
            c10.PopcornPointsBalance = 10;
            db.AppUsers.AddOrUpdate(c => c.LastName, c10);
            db.SaveChanges();

            User c11 = new User();
            c11.LastName = "Haley";
            c11.FirstName = "Charles";
            c11.Email = "chaley@thug.com";
            c11.Password = "onetime";
            c11.Birthday = new DateTime(1974, 7, 10);
            c11.StreetAddress = "One Cowboy Pkwy";
            c11.City = "Austin";
            c11.State = "TX";
            c11.ZipCode = 78712;
            c11.PhoneNumber = "5125550116";
            c11.PopcornPointsBalance = 40;
            db.AppUsers.AddOrUpdate(c => c.LastName, c11);
            db.SaveChanges();

            User c12 = new User();
            c12.LastName = "Hampton";
            c12.FirstName = "Jeffrey";
            c12.Email = "jeffh@sonic.com";
            c12.Password = "hampton1";
            c12.Birthday = new DateTime(2004, 3, 10);
            c12.StreetAddress = "337 38th St.";
            c12.City = "San Marcos";
            c12.State = "TX";
            c12.ZipCode = 78666;
            c12.PhoneNumber = "5125550150";
            c12.PopcornPointsBalance = 150;
            db.AppUsers.AddOrUpdate(c => c.LastName, c12);
            db.SaveChanges();

            User c13 = new User();
            c13.LastName = "Hearn";
            c13.FirstName = "John";
            c13.Email = "wjhearniii@umich.org";
            c13.Password = "jhearn22";
            c13.Birthday = new DateTime(1950, 8, 5);
            c13.StreetAddress = "4225 North First";
            c13.City = "Austin";
            c13.State = "TX";
            c13.ZipCode = 78705;
            c13.PhoneNumber = "5125550196";
            c13.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(c => c.LastName, c13);
            db.SaveChanges();

            User c14 = new User();
            c14.LastName = "Hicks";
            c14.FirstName = "Anthony";
            c14.Email = "ahick@yaho.com";
            c14.Password = "hickhickup";
            c14.Birthday = new DateTime(2004, 12, 8);
            c14.StreetAddress = ""32 NE Garden Ln., Ste 910"";
            c14.City = "Austin";
            c14.State = "TX";
            c14.ZipCode = 78712;
            c14.PhoneNumber = "5125550188";
            c14.PopcornPointsBalance = 60;
            db.AppUsers.AddOrUpdate(c => c.LastName, c14);
            db.SaveChanges();

            User c15 = new User();
            c15.LastName = "Ingram";
            c15.FirstName = "Brad";
            c15.Email = "ingram@jack.com";
            c15.Password = "ingram2015";
            c15.Birthday = new DateTime(2001, 9, 5);
            c15.StreetAddress = "6548 La Posada Ct.";
            c15.City = "New York";
            c15.State = "NY";
            c15.ZipCode = 10101;
            c15.PhoneNumber = "5125550116";
            c15.PopcornPointsBalance = 20;
            db.AppUsers.AddOrUpdate(c => c.LastName, c15);
            db.SaveChanges();

            User c16 = new User();
            c16.LastName = "Jacobs";
            c16.FirstName = "Todd";
            c16.Email = "toddj@yourmom.com";
            c16.Password = "toddy25";
            c16.Birthday = new DateTime(1999, 1, 20);
            c16.StreetAddress = "4564 Elm St.";
            c16.City = "Austin";
            c16.State = "TX";
            c16.ZipCode = 78729;
            c16.PhoneNumber = "5125550166";
            c16.PopcornPointsBalance = 170;
            db.AppUsers.AddOrUpdate(c => c.LastName, c16);
            db.SaveChanges();

            User c17 = new User();
            c17.LastName = "Lawrence";
            c17.FirstName = "Victoria";
            c17.Email = "thequeen@aska.net";
            c17.Password = "something";
            c17.Birthday = new DateTime(2000, 4, 14);
            c17.StreetAddress = "6639 Butterfly Ln.";
            c17.City = "Beverly Hills";
            c17.State = "CA";
            c17.ZipCode = 90210;
            c17.PhoneNumber = "5125550173";
            c17.PopcornPointsBalance = 130;
            db.AppUsers.AddOrUpdate(c => c.LastName, c17);
            db.SaveChanges();

            User c18 = new User();
            c18.LastName = "Lineback";
            c18.FirstName = "Erik";
            c18.Email = "linebacker@gogle.com";
            c18.Password = "Password1";
            c18.Birthday = new DateTime(2003, 12, 2);
            c18.StreetAddress = "1300 Netherland St";
            c18.City = "Austin";
            c18.State = "TX";
            c18.ZipCode = 78758;
            c18.PhoneNumber = "5125550167";
            c18.PopcornPointsBalance = 60;
            db.AppUsers.AddOrUpdate(c => c.LastName, c18);
            db.SaveChanges();

            User c19 = new User();
            c19.LastName = "Lowe";
            c19.FirstName = "Ernest";
            c19.Email = "elowe@netscare.net";
            c19.Password = "aclfest2017";
            c19.Birthday = new DateTime(1977, 12, 7);
            c19.StreetAddress = "3201 Pine Drive";
            c19.City = "New Braunfels";
            c19.State = "TX";
            c19.ZipCode = 78130;
            c19.PhoneNumber = "5125550187";
            c19.PopcornPointsBalance = 20;
            db.AppUsers.AddOrUpdate(c => c.LastName, c19);
            db.SaveChanges();

            User c20 = new User();
            c20.LastName = "Luce";
            c20.FirstName = "Chuck";
            c20.Email = "cluce@gogle.com";
            c20.Password = "nothinggood";
            c20.Birthday = new DateTime(1949, 3, 16);
            c20.StreetAddress = "2345 Rolling Clouds";
            c20.City = "Cactus";
            c20.State = "TX";
            c20.ZipCode = 79013;
            c20.PhoneNumber = "5125550141";
            c20.PopcornPointsBalance = 180;
            db.AppUsers.AddOrUpdate(c => c.LastName, c20);
            db.SaveChanges();

            User c21 = new User();
            c21.LastName = "MacLeod";
            c21.FirstName = "Jennifer";
            c21.Email = "mackcloud@george.com";
            c21.Password = "whatever";
            c21.Birthday = new DateTime(1947, 2, 21);
            c21.StreetAddress = "2504 Far West Blvd.";
            c21.City = "Marble Falls";
            c21.State = "TX";
            c21.ZipCode = 78654;
            c21.PhoneNumber = "5125550185";
            c21.PopcornPointsBalance = 170;
            db.AppUsers.AddOrUpdate(c => c.LastName, c21);
            db.SaveChanges();

            User c22 = new User();
            c22.LastName = "Markham";
            c22.FirstName = "Elizabeth";
            c22.Email = "cmartin@beets.com";
            c22.Password = "whocares";
            c22.Birthday = new DateTime(1972, 3, 20);
            c22.StreetAddress = "7861 Chevy Chase";
            c22.City = "Kissimmee";
            c22.State = "FL";
            c22.ZipCode = 34741;
            c22.PhoneNumber = "5125550134";
            c22.PopcornPointsBalance = 100;
            db.AppUsers.AddOrUpdate(c => c.LastName, c22);
            db.SaveChanges();

            User c23 = new User();
            c23.LastName = "Martin";
            c23.FirstName = "Clarence";
            c23.Email = "clarence@yoho.com";
            c23.Password = "xcellent";
            c23.Birthday = new DateTime(1992, 7, 19);
            c23.StreetAddress = "87 Alcedo St.";
            c23.City = "Austin";
            c23.State = "TX";
            c23.ZipCode = 78709;
            c23.PhoneNumber = "5125550151";
            c23.PopcornPointsBalance = 130;
            db.AppUsers.AddOrUpdate(c => c.LastName, c23);
            db.SaveChanges();

            User c24 = new User();
            c24.LastName = "Martinez";
            c24.FirstName = "Gregory";
            c24.Email = "gregmartinez@drdre.com";
            c24.Password = "snowsnow";
            c24.Birthday = new DateTime(1947, 5, 28);
            c24.StreetAddress = "8295 Sunset Blvd.";
            c24.City = "Red Rock";
            c24.State = "TX";
            c24.ZipCode = 78662;
            c24.PhoneNumber = "5125550120";
            c24.PopcornPointsBalance = 20;
            db.AppUsers.AddOrUpdate(c => c.LastName, c24);
            db.SaveChanges();

            User c25 = new User();
            c25.LastName = "Miller";
            c25.FirstName = "Charles";
            c25.Email = "cmiller@bob.com";
            c25.Password = "mydogspot";
            c25.Birthday = new DateTime(1990, 10, 15);
            c25.StreetAddress = "8962 Main St.";
            c25.City = "South Padre Island";
            c25.State = "TX";
            c25.ZipCode = 78597;
            c25.PhoneNumber = "5125550198";
            c25.PopcornPointsBalance = 20;
            db.AppUsers.AddOrUpdate(c => c.LastName, c25);
            db.SaveChanges();

            User c26 = new User();
            c26.LastName = "Nelson";
            c26.FirstName = "Kelly";
            c26.Email = "knelson@aoll.com";
            c26.Password = "spotmydog";
            c26.Birthday = new DateTime(1971, 7, 13);
            c26.StreetAddress = "2601 Red River";
            c26.City = "Disney";
            c26.State = "OK";
            c26.ZipCode = 74340;
            c26.PhoneNumber = "5125550177";
            c26.PopcornPointsBalance = 110;
            db.AppUsers.AddOrUpdate(c => c.LastName, c26);
            db.SaveChanges();

            User c27 = new User();
            c27.LastName = "Nguyen";
            c27.FirstName = "Joe";
            c27.Email = "joewin@xfactor.com";
            c27.Password = "joejoejoe";
            c27.Birthday = new DateTime(1984, 3, 17);
            c27.StreetAddress = "1249 4th SW St.";
            c27.City = "Del Rio";
            c27.State = "TX";
            c27.ZipCode = 78841;
            c27.PhoneNumber = "5125550174";
            c27.PopcornPointsBalance = 150;
            db.AppUsers.AddOrUpdate(c => c.LastName, c27);
            db.SaveChanges();

            User c28 = new User();
            c28.LastName = "O'Reilly";
            c28.FirstName = "Bill";
            c28.Email = "orielly@foxnews.cnn";
            c28.Password = "billyboy";
            c28.Birthday = new DateTime(1959, 7, 8);
            c28.StreetAddress = "8800 Gringo Drive";
            c28.City = "Austin";
            c28.State = "TX";
            c28.ZipCode = 78746;
            c28.PhoneNumber = "5125550167";
            c28.PopcornPointsBalance = 190;
            db.AppUsers.AddOrUpdate(c => c.LastName, c28);
            db.SaveChanges();

            User c29 = new User();
            c29.LastName = "Radkovich";
            c29.FirstName = "Anka";
            c29.Email = "ankaisrad@gogle.com";
            c29.Password = "radgirl";
            c29.Birthday = new DateTime(1966, 5, 19);
            c29.StreetAddress = "1300 Elliott Pl";
            c29.City = "Austin";
            c29.State = "TX";
            c29.ZipCode = 78712;
            c29.PhoneNumber = "5125550151";
            c29.PopcornPointsBalance = 120;
            db.AppUsers.AddOrUpdate(c => c.LastName, c29);
            db.SaveChanges();

            User c30 = new User();
            c30.LastName = "Rhodes";
            c30.FirstName = "Megan";
            c30.Email = "megrhodes@freserve.co.uk";
            c30.Password = "meganr34";
            c30.Birthday = new DateTime(1965, 3, 12);
            c30.StreetAddress = "4587 Enfield Rd.";
            c30.City = "Austin";
            c30.State = "TX";
            c30.ZipCode = 78705;
            c30.PhoneNumber = "5125550133";
            c30.PopcornPointsBalance = 190;
            db.AppUsers.AddOrUpdate(c => c.LastName, c30);
            db.SaveChanges();

            User c31 = new User();
            c31.LastName = "Rice";
            c31.FirstName = "Eryn";
            c31.Email = "erynrice@aoll.com";
            c31.Password = "ricearoni";
            c31.Birthday = new DateTime(1975, 4, 28);
            c31.StreetAddress = "3405 Rio Grande";
            c31.City = "Austin";
            c31.State = "TX";
            c31.ZipCode = 78785;
            c31.PhoneNumber = "5125550196";
            c31.PopcornPointsBalance = 190;
            db.AppUsers.AddOrUpdate(c => c.LastName, c31);
            db.SaveChanges();

            User c32 = new User();
            c32.LastName = "Rodriguez";
            c32.FirstName = "Jorge";
            c32.Email = "jorge@noclue.com";
            c32.Password = "jrod2017";
            c32.Birthday = new DateTime(1953, 12, 8);
            c32.StreetAddress = "6788 Cotter Street";
            c32.City = "Littlefield";
            c32.State = "TX";
            c32.ZipCode = 79339;
            c32.PhoneNumber = "5125550141";
            c32.PopcornPointsBalance = 20;
            db.AppUsers.AddOrUpdate(c => c.LastName, c32);
            db.SaveChanges();

            User c33 = new User();
            c33.LastName = "Rogers";
            c33.FirstName = "Allen";
            c33.Email = "mrrogers@lovelyday.com";
            c33.Password = "rogerthat";
            c33.Birthday = new DateTime(1973, 4, 22);
            c33.StreetAddress = "4965 Oak Hill";
            c33.City = "Austin";
            c33.State = "TX";
            c33.ZipCode = 78733;
            c33.PhoneNumber = "5125550189";
            c33.PopcornPointsBalance = 100;
            db.AppUsers.AddOrUpdate(c => c.LastName, c33);
            db.SaveChanges();

            User c34 = new User();
            c34.LastName = "Saint-Jean";
            c34.FirstName = "Olivier";
            c34.Email = "stjean@athome.com";
            c34.Password = "bunnyhop";
            c34.Birthday = new DateTime(1995, 2, 19);
            c34.StreetAddress = "255 Toncray Dr.";
            c34.City = "Austin";
            c34.State = "TX";
            c34.ZipCode = 78755;
            c34.PhoneNumber = "5125550152";
            c34.PopcornPointsBalance = 250;
            db.AppUsers.AddOrUpdate(c => c.LastName, c34);
            db.SaveChanges();

            User c35 = new User();
            c35.LastName = "Saunders";
            c35.FirstName = "Sarah";
            c35.Email = "saunders@pen.com";
            c35.Password = "penguin12";
            c35.Birthday = new DateTime(1978, 2, 19);
            c35.StreetAddress = "332 Avenue C";
            c35.City = "Austin";
            c35.State = "TX";
            c35.ZipCode = 78701;
            c35.PhoneNumber = "5125550146";
            c35.PopcornPointsBalance = 40;
            db.AppUsers.AddOrUpdate(c => c.LastName, c35);
            db.SaveChanges();

            User c36 = new User();
            c36.LastName = "Sewell";
            c36.FirstName = "William";
            c36.Email = "willsheff@email.com";
            c36.Password = "alaskaboy";
            c36.Birthday = new DateTime(2004, 12, 23);
            c36.StreetAddress = "2365 51st St.";
            c36.City = "El Paso";
            c36.State = "TX";
            c36.ZipCode = 79953;
            c36.PhoneNumber = "5125550192";
            c36.PopcornPointsBalance = 200;
            db.AppUsers.AddOrUpdate(c => c.LastName, c36);
            db.SaveChanges();

            User c37 = new User();
            c37.LastName = "Sheffield";
            c37.FirstName = "Martin";
            c37.Email = "sheffiled@gogle.com";
            c37.Password = "martin1234";
            c37.Birthday = new DateTime(1960, 5, 8);
            c37.StreetAddress = "3886 Avenue A";
            c37.City = "Balmorhea";
            c37.State = "TX";
            c37.ZipCode = 79718;
            c37.PhoneNumber = "5125550131";
            c37.PopcornPointsBalance = 130;
            db.AppUsers.AddOrUpdate(c => c.LastName, c37);
            db.SaveChanges();

            User c38 = new User();
            c38.LastName = "Smith";
            c38.FirstName = "John";
            c38.Email = "johnsmith187@aoll.com";
            c38.Password = "smitty444";
            c38.Birthday = new DateTime(1955, 6, 25);
            c38.StreetAddress = "23 Hidden Forge Dr.";
            c38.City = "Austin";
            c38.State = "TX";
            c38.ZipCode = 78760;
            c38.PhoneNumber = "5125550190";
            c38.PopcornPointsBalance = 130;
            db.AppUsers.AddOrUpdate(c => c.LastName, c38);
            db.SaveChanges();

            User c39 = new User();
            c39.LastName = "Stroud";
            c39.FirstName = "Dustin";
            c39.Email = "dustroud@mail.com";
            c39.Password = "dustydusty";
            c39.Birthday = new DateTime(1967, 7, 26);
            c39.StreetAddress = "1212 Rita Rd";
            c39.City = "Austin";
            c39.State = "TX";
            c39.ZipCode = 78734;
            c39.PhoneNumber = "5125550157";
            c39.PopcornPointsBalance = 90;
            db.AppUsers.AddOrUpdate(c => c.LastName, c39);
            db.SaveChanges();

            User c40 = new User();
            c40.LastName = "Stuart";
            c40.FirstName = "Eric";
            c40.Email = "estuart@anchor.net";
            c40.Password = "stewball";
            c40.Birthday = new DateTime(1947, 12, 4);
            c40.StreetAddress = "5576 Toro Ring";
            c40.City = "Kyle";
            c40.State = "TX";
            c40.ZipCode = 78640;
            c40.PhoneNumber = "5125550191";
            c40.PopcornPointsBalance = 170;
            db.AppUsers.AddOrUpdate(c => c.LastName, c40);
            db.SaveChanges();

            User c41 = new User();
            c41.LastName = "Stump";
            c41.FirstName = "Peter";
            c41.Email = "peterstump@noclue.com";
            c41.Password = "slowwind";
            c41.Birthday = new DateTime(1974, 7, 10);
            c41.StreetAddress = "1300 Kellen Circle";
            c41.City = "Philadelphia";
            c41.State = "PA";
            c41.ZipCode = 19123;
            c41.PhoneNumber = "5125550136";
            c41.PopcornPointsBalance = 50;
            db.AppUsers.AddOrUpdate(c => c.LastName, c41);
            db.SaveChanges();

            User c42 = new User();
            c42.LastName = "Tanner";
            c42.FirstName = "Jeremy";
            c42.Email = "jtanner@mustang.net";
            c42.Password = "tanner5454";
            c42.Birthday = new DateTime(1944, 1, 11);
            c42.StreetAddress = "4347 Almstead";
            c42.City = "Austin";
            c42.State = "TX";
            c42.ZipCode = 78747;
            c42.PhoneNumber = "5125550170";
            c42.PopcornPointsBalance = 190;
            db.AppUsers.AddOrUpdate(c => c.LastName, c42);
            db.SaveChanges();

            User c43 = new User();
            c43.LastName = "Taylor";
            c43.FirstName = "Allison";
            c43.Email = "taylordjay@aoll.com";
            c43.Password = "allyrally";
            c43.Birthday = new DateTime(1990, 11, 14);
            c43.StreetAddress = "467 Nueces St.";
            c43.City = "Austin";
            c43.State = "TX";
            c43.ZipCode = 78712;
            c43.PhoneNumber = "5125550160";
            c43.PopcornPointsBalance = 110;
            db.AppUsers.AddOrUpdate(c => c.LastName, c43);
            db.SaveChanges();

            User c44 = new User();
            c44.LastName = "Taylor";
            c44.FirstName = "Rachel";
            c44.Email = "rtaylor@gogle.com";
            c44.Password = "taylorbaylor";
            c44.Birthday = new DateTime(1976, 1, 18);
            c44.StreetAddress = "345 Longview Dr.";
            c44.City = "Austin";
            c44.State = "TX";
            c44.ZipCode = 78758;
            c44.PhoneNumber = "5125550127";
            c44.PopcornPointsBalance = 160;
            db.AppUsers.AddOrUpdate(c => c.LastName, c44);
            db.SaveChanges();

            User c45 = new User();
            c45.LastName = "Tee";
            c45.FirstName = "Frank";
            c45.Email = "teefrank@noclue.com";
            c45.Password = "teeoff22";
            c45.Birthday = new DateTime(1998, 9, 6);
            c45.StreetAddress = "5590 Lavell Dr";
            c45.City = "Austin";
            c45.State = "TX";
            c45.ZipCode = 78729;
            c45.PhoneNumber = "5125550161";
            c45.PopcornPointsBalance = 70;
            db.AppUsers.AddOrUpdate(c => c.LastName, c45);
            db.SaveChanges();

            User c46 = new User();
            c46.LastName = "Tucker";
            c46.FirstName = "Clent";
            c46.Email = "ctucker@alphabet.co.uk";
            c46.Password = "tucksack1";
            c46.Birthday = new DateTime(1943, 2, 25);
            c46.StreetAddress = "312 Main St.";
            c46.City = "Round Rock";
            c46.State = "TX";
            c46.ZipCode = 78665;
            c46.PhoneNumber = "5125550106";
            c46.PopcornPointsBalance = 150;
            db.AppUsers.AddOrUpdate(c => c.LastName, c46);
            db.SaveChanges();

            User c47 = new User();
            c47.LastName = "Velasco";
            c47.FirstName = "Allen";
            c47.Email = "avelasco@yoho.com";
            c47.Password = "meow88";
            c47.Birthday = new DateTime(1985, 9, 10);
            c47.StreetAddress = "679 W. 4th";
            c47.City = "Cedar Park";
            c47.State = "TX";
            c47.ZipCode = 78613;
            c47.PhoneNumber = "5125550170";
            c47.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(c => c.LastName, c47);
            db.SaveChanges();

            User c48 = new User();
            c48.LastName = "Vino";
            c48.FirstName = "Janet";
            c48.Email = "vinovino@grapes.com";
            c48.Password = "vinovino";
            c48.Birthday = new DateTime(1985, 2, 7);
            c48.StreetAddress = "189 Grape Road";
            c48.City = "Lockhart";
            c48.State = "TX";
            c48.ZipCode = 78644;
            c48.PhoneNumber = "5125550128";
            c48.PopcornPointsBalance = 160;
            db.AppUsers.AddOrUpdate(c => c.LastName, c48);
            db.SaveChanges();

            User c49 = new User();
            c49.LastName = "West";
            c49.FirstName = "Jake";
            c49.Email = "westj@pioneer.net";
            c49.Password = "gowest";
            c49.Birthday = new DateTime(1976, 1, 9);
            c49.StreetAddress = "RR 3287";
            c49.City = "Austin";
            c49.State = "TX";
            c49.ZipCode = 78705;
            c49.PhoneNumber = "2025550170";
            c49.PopcornPointsBalance = 70;
            db.AppUsers.AddOrUpdate(c => c.LastName, c49);
            db.SaveChanges();

            User c50 = new User();
            c50.LastName = "Winthorpe";
            c50.FirstName = "Louis";
            c50.Email = "winner@hootmail.com";
            c50.Password = "louielouie";
            c50.Birthday = new DateTime(1953, 4, 19);
            c50.StreetAddress = "2500 Padre Blvd";
            c50.City = "Austin";
            c50.State = "TX";
            c50.ZipCode = 78747;
            c50.PhoneNumber = "2025550141";
            c50.PopcornPointsBalance = 150;
            db.AppUsers.AddOrUpdate(c => c.LastName, c50);
            db.SaveChanges();

            User c51 = new User();
            c51.LastName = "Wood";
            c51.FirstName = "Reagan";
            c51.Email = "rwood@voyager.net";
            c51.Password = "woodyman1";
            c51.Birthday = new DateTime(2002, 12, 28);
            c51.StreetAddress = "447 Westlake Dr.";
            c51.City = "Austin";
            c51.State = "TX";
            c51.ZipCode = 78753;
            c51.PhoneNumber = "2025550128";
            c51.PopcornPointsBalance = 20;
            db.AppUsers.AddOrUpdate(c => c.LastName, c51);
            db.SaveChanges();

            User e1 = new User();
            e1.LastName = "Jacobs";
            e1.FirstName = "Todd";
            e1.Email = "t.jacobs@longhorncinema.com";
            e1.Password = "society";
            e1.Birthday = new DateTime(1958, 4, 25);
            e1.StreetAddress = "4564 Elm St.";
            e1.City = "Georgetown";
            e1.State = "TX";
            e1.ZipCode = 78628;
            e1.PhoneNumber = "9074653365";
            e1.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e1);
            db.SaveChanges();

            User e2 = new User();
            e2.LastName = "Rice";
            e2.FirstName = "Eryn";
            e2.Email = "e.rice@longhorncinema.com";
            e2.Password = "ricearoni";
            e2.Birthday = new DateTime(1959, 7, 2);
            e2.StreetAddress = "3405 Rio Grande";
            e2.City = "Austin";
            e2.State = "TX";
            e2.ZipCode = 78746;
            e2.PhoneNumber = "9073876657";
            e2.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e2);
            db.SaveChanges();

            User e3 = new User();
            e3.LastName = "Ingram";
            e3.FirstName = "Brad";
            e3.Email = "b.ingram@longhorncinema.com";
            e3.Password = "ingram45";
            e3.Birthday = new DateTime(1962, 8, 25);
            e3.StreetAddress = "6548 La Posada Ct.";
            e3.City = "Austin";
            e3.State = "TX";
            e3.ZipCode = 78705;
            e3.PhoneNumber = "9074678821";
            e3.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e3);
            db.SaveChanges();

            User e4 = new User();
            e4.LastName = "Taylor";
            e4.FirstName = "Allison";
            e4.Email = "a.taylor@longhorncinema.com";
            e4.Password = "nostalgic";
            e4.Birthday = new DateTime(1964, 9, 2);
            e4.StreetAddress = "467 Nueces St.";
            e4.City = "Austin";
            e4.State = "TX";
            e4.ZipCode = 78727;
            e4.PhoneNumber = "9074748452";
            e4.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e4);
            db.SaveChanges();

            User e5 = new User();
            e5.LastName = "Martinez";
            e5.FirstName = "Gregory";
            e5.Email = "g.martinez@longhorncinema.com";
            e5.Password = "fungus";
            e5.Birthday = new DateTime(1992, 3, 30);
            e5.StreetAddress = "8295 Sunset Blvd.";
            e5.City = "Austin";
            e5.State = "TX";
            e5.ZipCode = 78712;
            e5.PhoneNumber = "9078746718";
            e5.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e5);
            db.SaveChanges();

            User e6 = new User();
            e6.LastName = "Sheffield";
            e6.FirstName = "Martin";
            e6.Email = "m.sheffield@longhorncinema.com";
            e6.Password = "longhorns";
            e6.Birthday = new DateTime(1996, 12, 29);
            e6.StreetAddress = "3886 Avenue A";
            e6.City = "San Marcos";
            e6.State = "TX";
            e6.ZipCode = 78666;
            e6.PhoneNumber = "9075479167";
            e6.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e6);
            db.SaveChanges();

            User e7 = new User();
            e7.LastName = "MacLeod";
            e7.FirstName = "Jennifer";
            e7.Email = "j.macleod@longhorncinema.com";
            e7.Password = "smitty";
            e7.Birthday = new DateTime(1997, 6, 10);
            e7.StreetAddress = "2504 Far West Blvd.";
            e7.City = "Austin";
            e7.State = "TX";
            e7.ZipCode = 78705;
            e7.PhoneNumber = "9074748138";
            e7.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e7);
            db.SaveChanges();

            User e8 = new User();
            e8.LastName = "Tanner";
            e8.FirstName = "Jeremy";
            e8.Email = "j.tanner@longhorncinema.com";
            e8.Password = "tanman";
            e8.Birthday = new DateTime(1970, 8, 12);
            e8.StreetAddress = "4347 Almstead";
            e8.City = "Austin";
            e8.State = "TX";
            e8.ZipCode = 78712;
            e8.PhoneNumber = "9074590929";
            e8.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e8);
            db.SaveChanges();

            User e9 = new User();
            e9.LastName = "Rhodes";
            e9.FirstName = "Megan";
            e9.Email = "m.rhodes@longhorncinema.com";
            e9.Password = "countryrhodes";
            e9.Birthday = new DateTime(1970, 12, 18);
            e9.StreetAddress = "4587 Enfield Rd.";
            e9.City = "Austin";
            e9.State = "TX";
            e9.ZipCode = 78729;
            e9.PhoneNumber = "9073744746";
            e9.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e9);
            db.SaveChanges();

            User e10 = new User();
            e10.LastName = "Stuart";
            e10.FirstName = "Eric";
            e10.Email = "e.stuart@longhorncinema.com";
            e10.Password = "stewboy";
            e10.Birthday = new DateTime(1971, 3, 11);
            e10.StreetAddress = "5576 Toro Ring";
            e10.City = "Austin";
            e10.State = "TX";
            e10.ZipCode = 78758;
            e10.PhoneNumber = "9078178335";
            e10.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e10);
            db.SaveChanges();

            User e11 = new User();
            e11.LastName = "Miller";
            e11.FirstName = "Charles";
            e11.Email = "c.miller@longhorncinema.com";
            e11.Password = "squirrel";
            e11.Birthday = new DateTime(1972, 7, 20);
            e11.StreetAddress = "8962 Main St.";
            e11.City = "Austin";
            e11.State = "TX";
            e11.ZipCode = 78709;
            e11.PhoneNumber = "9077458615";
            e11.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e11);
            db.SaveChanges();

            User e12 = new User();
            e12.LastName = "Taylor";
            e12.FirstName = "Rachel";
            e12.Email = "r.taylor@longhorncinema.com";
            e12.Password = "swansong";
            e12.Birthday = new DateTime(1972, 12, 20);
            e12.StreetAddress = "345 Longview Dr.";
            e12.City = "Austin";
            e12.State = "TX";
            e12.ZipCode = 78746;
            e12.PhoneNumber = "9074512631";
            e12.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e12);
            db.SaveChanges();

            User e13 = new User();
            e13.LastName = "Lawrence";
            e13.FirstName = "Victoria";
            e13.Email = "v.lawrence@longhorncinema.com";
            e13.Password = "lottery";
            e13.Birthday = new DateTime(1973, 4, 28);
            e13.StreetAddress = "6639 Butterfly Ln.";
            e13.City = "Austin";
            e13.State = "TX";
            e13.ZipCode = 78712;
            e13.PhoneNumber = "9079457399";
            e13.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e13);
            db.SaveChanges();

            User e14 = new User();
            e14.LastName = "Rogers";
            e14.FirstName = "Allen";
            e14.Email = "a.rogers@longhorncinema.com";
            e14.Password = "evanescent";
            e14.Birthday = new DateTime(1978, 6, 21);
            e14.StreetAddress = "4965 Oak Hill";
            e14.City = "Austin";
            e14.State = "TX";
            e14.ZipCode = 78705;
            e14.PhoneNumber = "9078752943";
            e14.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e14);
            db.SaveChanges();

            User e15 = new User();
            e15.LastName = "Markham";
            e15.FirstName = "Elizabeth";
            e15.Email = "e.markham@longhorncinema.com";
            e15.Password = "monty3";
            e15.Birthday = new DateTime(1990, 5, 21);
            e15.StreetAddress = "7861 Chevy Chase";
            e15.City = "Austin";
            e15.State = "TX";
            e15.ZipCode = 78785;
            e15.PhoneNumber = "9074579845";
            e15.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e15);
            db.SaveChanges();

            User e16 = new User();
            e16.LastName = "Baker";
            e16.FirstName = "Christopher";
            e16.Email = "c.baker@longhorncinema.com";
            e16.Password = "hecktour";
            e16.Birthday = new DateTime(1993, 3, 16);
            e16.StreetAddress = "1245 Lake Anchorage Blvd.";
            e16.City = "Cedar Park";
            e16.State = "TX";
            e16.ZipCode = 78613;
            e16.PhoneNumber = "9075571146";
            e16.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e16);
            db.SaveChanges();

            User e17 = new User();
            e17.LastName = "Saunders";
            e17.FirstName = "Sarah";
            e17.Email = "s.saunders@longhorncinema.com";
            e17.Password = "rankmary";
            e17.Birthday = new DateTime(1997, 1, 5);
            e17.StreetAddress = "332 Avenue C";
            e17.City = "Austin";
            e17.State = "TX";
            e17.ZipCode = 78733;
            e17.PhoneNumber = "9073497810";
            e17.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e17);
            db.SaveChanges();

            User e18 = new User();
            e18.LastName = "Sewell";
            e18.FirstName = "William";
            e18.Email = "w.sewell@longhorncinema.com";
            e18.Password = "walkamile";
            e18.Birthday = new DateTime(1986, 5, 25);
            e18.StreetAddress = "2365 51st St.";
            e18.City = "Austin";
            e18.State = "TX";
            e18.ZipCode = 78755;
            e18.PhoneNumber = "9074510084";
            e18.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e18);
            db.SaveChanges();

            User e19 = new User();
            e19.LastName = "Mason";
            e19.FirstName = "Jack";
            e19.Email = "j.mason@longhorncinema.com";
            e19.Password = "changalang";
            e19.Birthday = new DateTime(1986, 6, 6);
            e19.StreetAddress = "444 45th St";
            e19.City = "Austin";
            e19.State = "TX";
            e19.ZipCode = 78701;
            e19.PhoneNumber = "9018833432";
            e19.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e19);
            db.SaveChanges();

            User e20 = new User();
            e20.LastName = "Jackson";
            e20.FirstName = "Jack";
            e20.Email = "j.jackson@longhorncinema.com";
            e20.Password = "offbeat";
            e20.Birthday = new DateTime(1986, 10, 16);
            e20.StreetAddress = "222 Main";
            e20.City = "Austin";
            e20.State = "TX";
            e20.ZipCode = 78760;
            e20.PhoneNumber = "9075554545";
            e20.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e20);
            db.SaveChanges();

            User e21 = new User();
            e21.LastName = "Nguyen";
            e21.FirstName = "Mary";
            e21.Email = "m.nguyen@longhorncinema.com";
            e21.Password = "landus";
            e21.Birthday = new DateTime(1988, 4, 5);
            e21.StreetAddress = "465 N. Bear Cub";
            e21.City = "Austin";
            e21.State = "TX";
            e21.ZipCode = 78734;
            e21.PhoneNumber = "9075524141";
            e21.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e21);
            db.SaveChanges();

            User e22 = new User();
            e22.LastName = "Barnes";
            e22.FirstName = "Susan";
            e22.Email = "s.barnes@longhorncinema.com";
            e22.Password = "rhythm";
            e22.Birthday = new DateTime(1993, 2, 22);
            e22.StreetAddress = "888 S. Main";
            e22.City = "Kyle";
            e22.State = "TX";
            e22.ZipCode = 78640;
            e22.PhoneNumber = "9556662323";
            e22.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e22);
            db.SaveChanges();

            User e23 = new User();
            e23.LastName = "Jones";
            e23.FirstName = "Lester";
            e23.Email = "l.jones@longhorncinema.com";
            e23.Password = "kindly";
            e23.Birthday = new DateTime(1996, 6, 29);
            e23.StreetAddress = "999 LeBlat";
            e23.City = "Austin";
            e23.State = "TX";
            e23.ZipCode = 78747;
            e23.PhoneNumber = "9886662222";
            e23.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e23);
            db.SaveChanges();

            User e24 = new User();
            e24.LastName = "Garcia";
            e24.FirstName = "Hector";
            e24.Email = "h.garcia@longhorncinema.com";
            e24.Password = "instrument";
            e24.Birthday = new DateTime(1997, 5, 13);
            e24.StreetAddress = "777 PBR Drive";
            e24.City = "Austin";
            e24.State = "TX";
            e24.ZipCode = 78712;
            e24.PhoneNumber = "9221114444";
            e24.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e24);
            db.SaveChanges();

            User e25 = new User();
            e25.LastName = "Silva";
            e25.FirstName = "Cindy";
            e25.Email = "c.silva@longhorncinema.com";
            e25.Password = "arched";
            e25.Birthday = new DateTime(1997, 12, 29);
            e25.StreetAddress = "900 4th St";
            e25.City = "Austin";
            e25.State = "TX";
            e25.ZipCode = 78758;
            e25.PhoneNumber = "9221113333";
            e25.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e25);
            db.SaveChanges();

            User e26 = new User();
            e26.LastName = "Lopez";
            e26.FirstName = "Marshall";
            e26.Email = "m.lopez@longhorncinema.com";
            e26.Password = "median";
            e26.Birthday = new DateTime(1996, 11, 4);
            e26.StreetAddress = "90 SW North St";
            e26.City = "Austin";
            e26.State = "TX";
            e26.ZipCode = 78729;
            e26.PhoneNumber = "9234442222";
            e26.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e26);
            db.SaveChanges();

            User e27 = new User();
            e27.LastName = "Larson";
            e27.FirstName = "Bill";
            e27.Email = "b.larson@longhorncinema.com";
            e27.Password = "approval";
            e27.Birthday = new DateTime(1999, 11, 14);
            e27.StreetAddress = "1212 N. First Ave";
            e27.City = "Round Rock";
            e27.State = "TX";
            e27.ZipCode = 78665;
            e27.PhoneNumber = "9795554444";
            e27.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e27);
            db.SaveChanges();

            User e28 = new User();
            e28.LastName = "Rankin";
            e28.FirstName = "Suzie";
            e28.Email = "s.rankin@longhorncinema.com";
            e28.Password = "decorate";
            e28.Birthday = new DateTime(1999, 12, 17);
            e28.StreetAddress = "23 Polar Bear Road";
            e28.City = "Austin";
            e28.State = "TX";
            e28.ZipCode = 78712;
            e28.PhoneNumber = "9893336666";
            e28.PopcornPointsBalance = 0;
            db.AppUsers.AddOrUpdate(e => e.LastName, e28);
            db.SaveChanges();




        }
    }
}